"use client";

import React, { useState, useEffect } from "react";
import { FileText, Download, Plus, Clock, CheckCircle2 } from "lucide-react";

export default function ReportsPage() {
  const [reports, setReports] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  const loadReports = () => {
    fetch("/api/reports")
      .then((res) => {
        if (res.status === 401) {
          window.location.href = "/login";
          return null;
        }
        return res.json();
      })
      .then((res) => {
        if (res?.success) setReports(res.data.reports || []);
      })
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    loadReports();
  }, []);

  const handleGenerate = async (format: "CSV" | "JSON") => {
    setGenerating(true);
    try {
      const res = await fetch("/api/reports", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ format }),
      });
      const data = await res.json();
      if (data.success) {
        loadReports();
        alert(`Report ${data.data.fileName} generated and stored safely!`);
      }
    } catch (e) {
      alert("Error generating report");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="space-y-6 pb-12">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800 pb-5">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-white">Reports & Exports</h1>
          <p className="text-xs text-slate-400 mt-1">
            Generate, schedule, and audit executive intelligence digests with formula injection security.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => handleGenerate("CSV")}
            disabled={generating}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-blue-600 hover:bg-blue-500 text-white text-xs font-semibold shadow-lg shadow-blue-600/20 transition disabled:opacity-50"
          >
            <Plus className="h-3.5 w-3.5" />
            <span>Generate CSV Report</span>
          </button>
          <button
            onClick={() => handleGenerate("JSON")}
            disabled={generating}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-900 border border-slate-800 text-xs text-slate-300 hover:text-white transition disabled:opacity-50"
          >
            <Plus className="h-3.5 w-3.5" />
            <span>Generate JSON Digest</span>
          </button>
        </div>
      </div>

      <div className="p-5 rounded-xl bg-slate-900/80 border border-slate-800 space-y-4">
        <h3 className="text-sm font-bold text-white">Report History ({reports.length})</h3>

        <div className="divide-y divide-slate-800/60">
          {reports.map((rep) => (
            <div key={rep.id} className="py-3.5 flex items-center justify-between text-xs">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-blue-500/10 text-blue-400">
                  <FileText className="h-4 w-4" />
                </div>
                <div>
                  <div className="font-semibold text-white">{rep.title}</div>
                  <div className="text-[11px] text-slate-400">
                    Generated by {rep.generatedBy?.firstName || "System"} • Format: {rep.format} • {new Date(rep.createdAt).toLocaleString()}
                  </div>
                </div>
              </div>

              <div className="flex items-center gap-2">
                <span className="px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 text-[10px] font-semibold border border-emerald-500/20">
                  Archived & Encrypted
                </span>
                <a
                  href={`/api/reports/${rep.id}/download`}
                  download
                  className="flex items-center gap-1 px-2.5 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-200 hover:text-white text-[11px] font-medium border border-slate-700 transition"
                  title="Download report file securely"
                >
                  <Download className="h-3 w-3" />
                  <span>Download</span>
                </a>
              </div>
            </div>
          ))}

          {reports.length === 0 && (
            <div className="py-8 text-center text-xs text-slate-400">
              No reports generated yet. Click "Generate CSV Report" to create your first executive summary.
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

